# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
Data models for the Api Drift Env Environment.

The api_drift_env environment is a simple test environment that echoes back messages.
"""

from openenv.core.env_server.types import Action, Observation
from pydantic import Field


from typing import Optional, Dict, Any
from openenv.core.env_server.types import Action, Observation
from pydantic import Field


class ApiDriftAction(Action):
    """Action for the Api Drift Env environment."""
    raw: str = Field(..., description="The raw action string generated by the agent")


class ApiDriftObservation(Observation):
    """Observation from the Api Drift Env environment."""
    last_action: str = Field(default="", description="The action that was executed")
    api_response: str = Field(default="", description="The response from the API")
    error_message: str = Field(default="", description="Any error message that occurred")
    available_hint: Optional[Dict[str, Any]] = Field(default=None, description="Hints like workflow data")
    step_count: int = Field(default=0, description="Current step count")
    workflow_step: int = Field(default=0, description="Current workflow stage index")
    current_endpoint: Optional[str] = Field(default=None, description="The active endpoint")
    difficulty: Optional[str] = Field(default=None, description="Difficulty level")
